from enum import Enum


class Categories(Enum):
    ARTS = 'Arts_Crafts_and_Sewing'
    AUTOMOTIVE = 'Automotive'
    BEAUTY = 'All_Beauty'
    CDS = 'CDs_and_Vinyl'
    CELLPHONES = 'Cell_Phones_and_Accessories'
    CLOTHING = 'Clothing_Shoes_and_Jewelry'
    ELECTRONICS = 'Electronics'
    FASHION = 'AMAZON_FASHION'
    GROCERY = 'Grocery_and_Gourmet_Food'
    HOME = 'Home_and_Kitchen'
    INDUSTRIAL = 'Industrial_and_Scientific'
    INSTRUMENTS = 'Musical_Instruments'
    KINDLE = 'Kindle_Store'
    LUXURY = 'Luxury_Beauty'
    MAGAZINES = 'Magazine_Subscriptions'
    MOVIES = 'Movies_and_TV'
    MUSIC = 'Digital_Music'
    PATIO = 'Patio_Lawn_and_Garden'
    PANTRY = 'Prime_Pantry'
    SOFTWARE = 'Software'
    SPORTS = 'Sports_and_Outdoors'
    TOOLS = 'Tools_and_Home_Improvement'
    TOYS = 'Toys_and_Games'
    GAMES = 'Video_Games'
